### ISSUE TITLE
No LICENSE file for ordinal_array

### ISSUE THREAD

**Issue by clintoncwolfe** [kdisneur/ordinal_array#1]
Hello!  My team and I are using ordinal_array as a test article in a gem installation system - it's small, low-impact, and predictable.  Currently there is no license listed, which makes us unsure if we can use it (and in particular, redistribute it).

Could you provide a license file?

Thanks!

**Comment by kdisneur** [comment]
To be honest I never used this project. 
It was more of a pet project to learn Ruby but, if it can help you, I can add an MIT license.

**Comment by kdisneur** [comment]
Ok - I just generated a MIT file: https://github.com/kdisneur/ordinal_array/blob/master/LICENSE.md

Feel free to reopen if you need more :)
